"""
Trading signal model.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from dataclasses import field

from src.analysis.analysis_fact import AnalysisFact
from src.models.enums import SignalType


@dataclass(slots=True)
class Signal:
    """
    Represents a BUY or SELL signal generated by a scanner.

    This model represents a scanner recommendation only.
    It does NOT represent an executed trade or an open position.
    """

    # Instrument
    security_id: int

    # Scanner information
    strategy: str
    signal_type: SignalType

    # Prices
    signal_price: float
    current_ltp: float

    # Confidence score (0-100)
    confidence: float

    # Human readable explanation
    message: str

    # Signal timestamp
    timestamp: datetime = field(default_factory=datetime.now)

    # Signal lifecycle
    is_active: bool = True

    # Additional scanner-specific information
    metadata: dict[str, str] = field(default_factory=dict)

    #
    # Raw score before normalization
    #
    raw_score: float = 0.0

    #
    # Final normalized percentage
    #
    score_percentage: float = 0.0

    #
    # Technical analysis facts
    #
    analysis_facts: list[AnalysisFact] = field(
        default_factory=list
    )

    #
    # Score contribution
    #
    score_breakdown: dict[str, float] = field(
        default_factory=dict
    )